### ISSUE TITLE
C# FirewallArgs.DropletIds Property InputList<int> Droplet.Id Output<string>

### ISSUE THREAD

**Issue by napalm684** [pulumi/pulumi-digitalocean#248] opened 2021-07-24 02:54 UTC
There appears to be a type mismatch here with the firewall droplet ids wanting int values and droplet exporting strings

## Steps to reproduce
Create a droplet and a firewall, try to pass in `droplet.id` as the `DropletIds` value

Expected:  The value to be accepted.
Actual: Compiler complains of type mismatch

Same issue as TypeScript https://github.com/pulumi/pulumi-digitalocean/issues/81

**Comment by leezen** [comment] 2021-07-26 19:17
Duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/352

**Closed by leezen** 2021-07-26 19:17 UTC
Labels: kind/bug, resolution/duplicate
