### ISSUE TITLE
[dotnet] Unable to create Kubernetes cluster due to missing required arguments

### ISSUE THREAD

**Issue by Calance96** [pulumi/pulumi-digitalocean#470] opened 2023-08-22 00:40 UTC
### What happened?

When attempting to create Kubernetes cluster in Digital Ocean, errors are thrown indicating that required arguments are missing. 

**Errors**
![image](https://github.com/pulumi/pulumi-digitalocean/assets/23103571/70c27429-e10d-4bb9-b4b5-192c33e655ac)

**Versions**
```
Pulumi CLI: 3.78.1

Dependencies:
NAME                 VERSION
Pulumi               3.56.0
Pulumi.DigitalOcean  4.21.0
Pulumi.Docker        4.3.1
Pulumi.Kubernetes    4.1.0
```

**Configuration C# code**
```csharp
Vpc vpc = new(
	"backend-k8s-vpc",
	new()
	{
		Region = Region.SGP1.ToString(),
		Name = "backend-vpc",
		IpRange = "10.0.0.0/16"
	});

KubernetesCluster backendK8SCluster = new(
	"backend-k8s-cluster",
	new()
	{
		Region = Region.SGP1,
		Name = "k8s-cluster",
		Version = "1.27.4-do.0",
		Tags = new[] { "backend" },
		VpcUuid = vpc.Id,
		NodePool = new KubernetesClusterNodePoolArgs()
		{
			Name = "backend-node-pool",
			Size = DropletSlug.DropletS2VCPU4GB.ToString(),
			NodeCount = 1,
			Tags = new[] { "backend" },
			Labels =
			{
				{ "service", "backend" }
			}
		}
	},
	new()
	{
		DependsOn = vpc
	});
```

### Expected Behavior

Should be able to create the cluster successfully without any error. This is the same setup that I used in my previous project.

### Steps to reproduce

Use the code snippet attached and run `pulumi preview` or `pulumi up`.

### Output of `pulumi about`

```
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME          VERSION
digitalocean  4.21.0
docker        4.3.1
dotnet        unknown
kubernetes    4.1.0

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.400-preview.23330.10'

Dependencies:
NAME                 VERSION
Pulumi               3.56.0
Pulumi.DigitalOcean  4.21.0
Pulumi.Docker        4.3.1
Pulumi.Kubernetes    4.1.0
```

**Comment by danielrbradley** [comment] 2023-08-22 16:01
Thanks for getting in touch @Calance96 

I've just run a full deployment in C# using the code you posted above, version 4.21.0 of the provider and v3.78.1 of Pulumi and the whole deployment completed without error. 

I notice that your example uses the name `backend-k8s-cluster` but the error messages mention `k8s-cluster`. I'm going to close this as can't reproduce but please do open a new issue if you've got a program which produces the issue you're seeing.

**Closed** 2023-08-22 16:01 UTC
Labels: kind/bug, resolution/no-repro

**Comment by Calance96** [comment] 2023-08-23 01:11
@danielrbradley hello, thank you for looking into it. The `k8s-cluster` is from the `KubernetesClusterArgs`. Weird though as I am still able to reproduce on my end :/

**Comment by Calance96** [comment] 2023-08-23 01:53
Ok, I found the issue, turns out the problem lied within the creation of `Pulumi.Kubernetes.Provider` when reading `kubeConfig` from the cluster. I changed the way of reading it and now it is working fine.
