### ISSUE TITLE
golang: ID of a droplet is of type StringOutput incompatible with other Ressources

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-digitalocean#244] opened 2021-06-13 11:54 UTC
Version: github.com/pulumi/pulumi-digitalocean/sdk/v4 v4.4.1
golang: 1.16

Currently, when you create a droplet the ID is of type StringOutput. 

The problem is, when you wanto to create any other resource (eg. FloatingIpAssignment, VolumeAttachment or FloatingIp) you need the ID of type IntInput.

## Steps to reproduce

1.
Create a Droplet:

```go
droplet, err := do.NewDroplet(ctx, args.StackName, &do.DropletArgs{
	Name:     pulumi.String(args.StackName),
	Image:    pulumi.String("ubuntu-20-10-x64"),
	Region:   pulumi.String(args.Region),
	Size:     pulumi.String(args.Size),
})
```

2.

Create FloatingIP

```go
fip, err := do.NewFloatingIp(ctx, "floating", &do.FloatingIpArgs{
	Region: droplet.Region,
})
```

3.

```go
do.NewFloatingIpAssignment(ctx, "floating-ip-assignment", &do.FloatingIpAssignmentArgs{
	IpAddress: fip.IpAddress,
	DropletId: pulumi.Int(droplet.ID()),
})
```

Expected: Works
Actual: 
![image](https://user-images.githubusercontent.com/38325136/121806028-4c9ff980-cc4e-11eb-8371-d62a957cda83.png)

Current Workaround:

With ApplyT and LookupDroplet 😢 
```go
_ = droplet.Name.ApplyT(func(id string) string {
	lookup, _ := do.LookupDroplet(ctx, &do.LookupDropletArgs{
		Name: &id,
	}, nil)

	do.NewFloatingIpAssignment(ctx, "floating-ip-assignment", &do.FloatingIpAssignmentArgs{
		IpAddress: fip.IpAddress,
		DropletId: pulumi.Int(lookup.Id),
	})
	return id
}).(pulumi.StringOutput)
```

Maybe i using it wrong, any feedback is welcome.

**Comment by leezen** [comment] 2021-06-15 22:23
Duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/352

**Closed by leezen** 2021-06-15 22:23 UTC
Labels: kind/bug, resolution/duplicate
