### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by douglasg14b** [pulumi/pulumi-digitalocean#762] opened 2024-06-26 00:01 UTC
### What happened?

When trying to run `pulumi up` I get:

```
Diagnostics:
  digitalocean:index:App (hiveAppService-prod):
    error: error reading from server: read tcp 127.0.0.1:56198->127.0.0.1:56195: wsarecv: An existing connection was forcibly closed by the remote host.

  pulumi:pulumi:Stack (hive-prod):
    panic: runtime error: index out of range [0] with length 0
    goroutine 46 [running]:
    github.com/digitalocean/terraform-provider-digitalocean/digitalocean/app.expandAppCORSPolicy({0xc000a9ef30?, 0xc000882180?, 0x205cf6b?})
        /home/runner/work/pulumi-digitalocean/pulumi-digitalocean/upstream/digitalocean/app/app_spec.go:2066 +0xb45
    github.com/digitalocean/terraform-provider-digitalocean/digitalocean/app.expandAppIngress({0xc000a9eea0, 0xc00140fe60?, 0x2061a22?})
        /home/runner/work/pulumi-digitalocean/pulumi-digitalocean/upstream/digitalocean/app/app_spec.go:2154 +0x72c
    github.com/digitalocean/terraform-provider-digitalocean/digitalocean/app.expandAppSpec({0xc000a9ece0?, 0x205c537?, 0x1a3185c5000?})
        /home/runner/work/pulumi-digitalocean/pulumi-digitalocean/upstream/digitalocean/app/app_spec.go:1052 +0xc05
    github.com/digitalocean/terraform-provider-digitalocean/digitalocean/app.resourceDigitalOceanAppCreate({0x2587888, 0xc0004dbb20}, 0xc000815000, {0x1e5e760?, 0xc00031c8a0?})
        /home/runner/work/pulumi-digitalocean/pulumi-digitalocean/upstream/digitalocean/app/resource_app.go:123 +0xce
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0005e5260, {0x25877e0, 0xc0007f5b60}, 0xd?, {0x1e5e760, 0xc00031c8a0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/resource.go:778 +0x11b
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005e5260, {0x25877e0, 0xc0007f5b60}, 0x0, 0xc000b43d00, {0x1e5e760, 0xc00031c8a0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/resource.go:909 +0xa89
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0xc00081c420?, {0x0?, 0xc000dc7400?, 0xc000dc7598?}}, {0x25877e0, 0xc0007f5b60}, {0x206f708, 0x10}, {0x0, 0x0}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfshim/sdk-v2/provider.go:131 +0x185
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc0005cf300, {0x25877e0?, 0xc0007f5740?}, 0xc0007f6000)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfbridge/provider.go:1159 +0x8b1
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x25877e0, 0xc0007f5740}, {0x1f77820?, 0xc0007f6000})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.118.0/proto/go/provider_grpc.pb.go:651 +0x72
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x25877e0, 0xc0007f4000}, {0x1f77820, 0xc0007f6000}, 0xc000dba0a0, 0xc0007d40f0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x2027c00?, 0xc0005cf300}, {0x25877e0, 0xc0007f4000}, 0xc0007f2000, 0xc0008abf80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.118.0/proto/go/provider_grpc.pb.go:653 +0x135
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000bfda00, {0x25877e0, 0xc000d02150}, {0x25917e0, 0xc000002a80}, 0xc000d12000, 0xc000883b30, 0x32285b8, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
    google.golang.org/grpc.(*Server).handleStream(0xc000bfda00, {0x25917e0, 0xc000002a80}, 0xc000d12000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 57
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

    error: update failed

Resources:
    9 unchanged

Duration: 9s
```

### Example

Unknown

### Output of `pulumi about`

```
CLI
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  digitalocean  4.30.2
language  nodejs        unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v20.10.0'

Current Stack: douglasg14b/hive/prod

TYPE                                                                            URN
pulumi:pulumi:Stack                                                             urn:pulumi:prod::hive::pulumi:pulumi:Stack::hive-prod
pulumi:providers:digitalocean                                                   urn:pulumi:prod::hive::pulumi:providers:digitalocean::default_4_30_2
digitalocean:index/spacesBucket:SpacesBucket                                    urn:pulumi:prod::hive::digitalocean:index/spacesBucket:SpacesBucket::hiveThumbnailsBucket-prod
digitalocean:index/spacesBucket:SpacesBucket                                    urn:pulumi:prod::hive::digitalocean:index/spacesBucket:SpacesBucket::hiveCreativesBucket-prod
digitalocean:index/vpc:Vpc                                                      urn:pulumi:prod::hive::digitalocean:index/vpc:Vpc::hiveServiceVpc-prod
digitalocean:index/spacesBucketCorsConfiguration:SpacesBucketCorsConfiguration  urn:pulumi:prod::hive::digitalocean:index/spacesBucketCorsConfiguration:SpacesBucketCorsConfiguration::hiveThumbnailsBucketCors-prod
digitalocean:index/spacesBucketCorsConfiguration:SpacesBucketCorsConfiguration  urn:pulumi:prod::hive::digitalocean:index/spacesBucketCorsConfiguration:SpacesBucketCorsConfiguration::hiveCreativesBucketCors-prod
digitalocean:index/databaseCluster:DatabaseCluster                              urn:pulumi:prod::hive::digitalocean:index/databaseCluster:DatabaseCluster::hiveDatabaseCluster-prod
digitalocean:index/databaseUser:DatabaseUser                                    urn:pulumi:prod::hive::digitalocean:index/databaseUser:DatabaseUser::hiveDatabaseUser-prod
digitalocean:index/databaseDb:DatabaseDb                                        urn:pulumi:prod::hive::digitalocean:index/databaseDb:DatabaseDb::hiveDatabase-prod


Found no pending operations associated with prod

Backend
Name           pulumi.com
URL            https://app.pulumi.com/douglasg14b
User           douglasg14b
Organizations  douglasg14b
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment] 2024-06-26 10:03
possible duplicate of https://github.com/pulumi/pulumi-digitalocean/issues/658

**Comment by justinvp** [comment] 2024-06-26 15:51
> possible duplicate of #658

Ah, I looked for an existing issue, but missed that one. We should just close this one as a duplicate.

@douglasg14b, any chance you could a share your Pulumi program (or minimal version of it) that panics?

**Comment by iwahbe** [comment] 2024-06-26 16:35
This looks like a duplicate of https://github.com/pulumi/pulumi-digitalocean/issues/658. @douglasg14b Please post a repro for this issue in #658.

**Closed by iwahbe** 2024-06-26 16:35 UTC
Labels: kind/bug, resolution/duplicate, impact/panic

**Comment by douglasg14b** [comment] 2024-06-27 00:09
Ah, that explains why I couldn't find the other issue.

I know I made one, but couldn't find it on the pulumi repo, so I opened another.

Thanks.
