### ISSUE TITLE
panic: fatal: An assertion has failed error

### ISSUE THREAD

**Issue by jodysalt** [pulumi/pulumi-digitalocean#341] opened 2022-11-13 14:58 UTC
### What happened?

The pulumi cli  crashes with a `panic: fatal: An assertion has failed` error.

### Steps to reproduce

```typescript
import * as digitalocean from "@pulumi/digitalocean";
import * as kubernetes from "@pulumi/kubernetes";
import * as certmanager from "@pulumi/kubernetes-cert-manager";

const cluster = new digitalocean.KubernetesCluster("do-cluster", {
    region: digitalocean.Region.LON1,
    version: digitalocean.getKubernetesVersions().then(p => p.latestVersion),
    nodePool: {
        name: "default",
        size: digitalocean.DropletSlug.DropletS2VCPU2GB,
        nodeCount: 2,
    },
});

export const kubeconfig = cluster.status.apply(status => {
    if (status === "running") {
        const clusterDataSource = cluster.name.apply(name => digitalocean.getKubernetesCluster({ name }));
        return clusterDataSource.kubeConfigs[0].rawConfig;
    } else {
        return cluster.kubeConfigs[0].rawConfig;
    }
});

const provider = new kubernetes.Provider("do-k8s", { kubeconfig });

const certManagerNamespace = new kubernetes.core.v1.Namespace("do-cert-manager-namespace", {
    metadata: { name: 'cert-manager' },
}, { provider });

const certManager = new certmanager.CertManager("do-cert-manager", {
    installCRDs: true,
    helmOptions: {
        namespace: certManagerNamespace.metadata.name,
    },
}, { provider });
```

then run:

```
DIGITALOCEAN_TOKEN=MY_SECRET_TOKEN pulumi up --stack prod 
```

### Expected Behavior

I get a prompt asking me if I want to create stack resources.

### Actual Behavior

It crashes with the following:

```
panic: fatal: An assertion has failed

goroutine 194 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
private/tmp/pulumi-20221109-4783-xtvj6j/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
/private/tmp/pulumi-20221109-4783-xtvj6j/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*provider).Construct(0xc0006e05a0, {{0xc00029d8d8, 0x3}, {0xc00065ffd4, 0x4}, 0xc0009f01b0, {0x0, 0x0, 0x0}, 0x1, ...}, ...)
/private/tmp/pulumi-20221109-4783-xtvj6j/sdk/go/common/resource/plugin/provider_plugin.go:1201 +0x11b4
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*resmon).RegisterResource(0xc00063f1e0, {0xc00149b858?, 0x1003d96f5?}, 0xc0015221a0)
/private/tmp/pulumi-20221109-4783-xtvj6j/pkg/resource/deploy/source_eval.go:1201 +0x27b9
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceMonitor_RegisterResource_Handler.func1({0x10249a718, 0xc0006ed5f0}, {0x101e8ea20?, 0xc0015221a0})
/private/tmp/pulumi-20221109-4783-xtvj6j/sdk/proto/go/resource.pb.go:1713 +0x78
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10249a718, 0xc0006ed3e0}, {0x101e8ea20, 0xc0015221a0}, 0xc0006e8160, 0xc001500c30)
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceMonitor_RegisterResource_Handler({0x101dbe3a0?, 0xc00063f1e0}, {0x10249a718, 0xc0006ed3e0}, 0xc001526000, 0xc0000a7220)
/private/tmp/pulumi-20221109-4783-xtvj6j/sdk/proto/go/resource.pb.go:1715 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b71860, {0x1024a4c20, 0xc00023c340}, 0xc00151ec60, 0xc0009f0480, 0x1034b3580, 0x0)
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc000b71860, {0x1024a4c20, 0xc00023c340}, 0xc00151ec60, 0x0)
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a
```

### Output of `pulumi about`

```
CLI          
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.0.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.14.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jodysalt
User           jodysalt
Organizations  jodysalt

Pulumi locates its logs in /var/folders/12/sr3mv4j54079by205f785bdh0000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/jody/software/blognami-saas/iac/yarn.lock or /Users/jody/software/blognami-saas/iac/package-lock.json
warning: Failed to get information about the current stack: No current stack
```

### Additional context

If I remove:

```typescript
const certManager = new certmanager.CertManager("do-cert-manager", {
    installCRDs: true,
    helmOptions: {
        namespace: certManagerNamespace.metadata.name,
    },
}, { provider });
```

it doesn't crash.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2022-11-15 15:01
Hi @jodysalt, thank you for the detailed report. I believe you're running into an unfortunate interaction between the DigitalOcean provider and the Kubernetes providers. The Kubernetes provider, and, as a consequence, the CertManager, [need a kubeconfig](https://www.pulumi.com/registry/packages/kubernetes/installation-configuration/#setup). Since you're using Kubernetes via DigitalOcean, it doesn't exist yet until the cluster is created - it's [an `Output` of the cluster](https://www.pulumi.com/registry/packages/digitalocean/api-docs/kubernetescluster/#outputs).

One way to work around this is to use two separate stacks, one for DigitalOcean and one for the Kubernetes providers. That way, you can take the kubeconfig from the output from the DigitalOcean stack and use it in the other stack via a [stack reference](https://www.pulumi.com/learn/building-with-pulumi/stack-references/).

Sorry for the obscure `panic` here instead of a clear error, we'll make a note to improve this.

**Comment by jodysalt** [comment] 2022-11-18 18:02
Thanks @thomas11 for getting back to me.

The only thing I still find puzzling is it has worked in the past. Has something fundamentally changed? It feels like a bit of a smell to me.

I will give your suggestion a go. Thanks again 👍

**Comment by thomas11** [comment] 2022-11-18 18:49
It certainly is a smell! Let me know how it goes.

**Comment by mikhailshilkov** [comment] 2023-07-28 13:13
Since it's been a while, I'll assume the issue was resolved and close it. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!

**Closed by mikhailshilkov** 2023-07-28 13:13 UTC
Labels: kind/bug, resolution/by-design, impact/panic
